### ISSUE TITLE
32px title bar

### ISSUE THREAD

**Issue by b1ack0p** [sevmeyer/mowi-xfwm4#1]
Hi. thank you for this lovely theme but may i ask a favor? when i use mowi-24 window title bar is too tiny, if i use mowi-48 then it is too wide/big. Is it possible to make it 32px? that would be optimum size for window title bar imo.

by the way, i am talking physical theme files which i downloaded here: https://www.xfce-look.org/p/1700122/

i changed your theme a bit to modify raspberrypiOS theme for xfce/xfwm4 here: https://github.com/b1ack0p/PiXflat-xfce-theme but when i manually edited title bar size to 32px it lost the ability to pick system colors automatically. I had to color buttons and bars manually same with the main theme color. how to activate the ability of picking system colors for the modified theme?

if you can help me in this matter i will be more than happy.

thanks in advance!

**Comment by sevmeyer** [comment]
Make sure to check the Xfwm wiki, especially for the [Gtk Color pickup](https://wiki.xfce.org/howto/xfwm4_theme#gtk_color_pickup) and [XPM format](https://wiki.xfce.org/howto/xfwm4_theme#xpm_x_pixmap_format). You need to include the symbolic GTK name after the color, for example:

    /* XPM */
    static char *close_active[] = {
    "40 48 3 1 ",
    "  c #444444 s active_shadow_1",
    ". c #555555 s active_color_1",
    "X c #EEEEEE s active_text_color",
    ...

I might find some time to add a 32px/64px version. However, if you would like rounder corners or other stylistic changes, you will have to adapt it yourself.

**Comment by b1ack0p** [comment]
thank you very much for your response. if you can add 32px/64px that would be great! I edited corners yesterday so i could make rounder corners finally. but as i mentioned earlier when i make changes on XPM image files via GIMP, it looses the ability to pick system colors. I will read wiki. thanks a lot again.

**Comment by sevmeyer** [comment]
XPM is a text-based format, you can open it with any text editor.

I have added size 32 and 64, see the [release page](https://github.com/sevmeyer/mowi-xfwm4/releases/tag/1.1).

**Comment by b1ack0p** [comment]
thank you for 32px and 64px!
